In [3]:
# importing all neseccary Pyhton packages

import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [5]:
# laading data into pannds dataframe 

hospital_data = pd.read_csv('Readmissions_and_Deaths.csv')

In [8]:
hospital_data.head()

,index,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Measure Name,Measure ID,Compared to National,Denominator,Score,Lower Estimate,Higher Estimate,Footnote,Measure Start Date,Measure End Date,Location
0,0,230100,TAWAS ST JOSEPH HOSPITAL,200 HEMLOCK,TAWAS CITY,MI,48764,IOSCO,9893629301,Rate of readmission after discharge from hospi...,READM_30_HOSP_WIDE,No Different than the National Rate,438,13.9,12.6,15.6,NaN,07/01/2014,06/30/2015,"200 HEMLOCK\nTAWAS CITY, MI 48764\n(44.274911,..."
1,1,230121,MEMORIAL HEALTHCARE,826 WEST KING STREET,OWOSSO,MI,48867,SHIAWASSEE,9897235211,Rate of readmission after hip/knee replacement,READM_30_HIP_KNEE,No Different than the National Rate,150,4.0,2.8,5.7,NaN,07/01/2012,06/30/2015,"826 WEST KING STREET\nOWOSSO, MI 48867\n(43.00..."
2,2,230118,HURON MEDICAL CENTER,1100 SOUTH VAN DYKE ROAD,BAD AXE,MI,48413,HURON,9892699521,Pneumonia (PN) 30-Day Readmission Rate,READM_30_PN,No Different than the National Rate,205,16.7,13.8,19.9,NaN,07/01/2012,06/30/2015,"1100 SOUTH VAN DYKE ROAD\nBAD AXE, MI 48413\n(..."
3,3,230121,MEMORIAL HEALTHCARE,826 WEST KING STREET,OWOSSO,MI,48867,SHIAWASSEE,9897235211,Rate of readmission for stroke patients,READM_30_STK,No Different than the National Rate,67,11.5,8.7,14.9,NaN,07/01/2012,06/30/2015,"826 WEST KING STREET\nOWOSSO, MI 48867\n(43.00..."
4,4,230133,OTSEGO MEMORIAL HOSPITAL,825 N CENTER AVE,GAYLORD,MI,49735,OTSEGO,9897312100,Heart failure (HF) 30-Day Mortality Rate,MORT_30_HF,No Different than the National Rate,102,13.4,9.9,17.7,NaN,07/01/2012,06/30/2015,"825 N CENTER AVE\nGAYLORD, MI 49735\n(45.03537..."

In [11]:
hospital_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64764 entries, 0 to 64763
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 64764 non-null  int64
 1   Provider ID           64764 non-null  int64
 2   Hospital Name         64764 non-null  object
 3   Address               64764 non-null  object
 4   City                  64764 non-null  object
 5   State                 64764 non-null  object
 6   ZIP Code              64764 non-null  int64
 7   County Name           64582 non-null  object
 8   Phone Number          64764 non-null  int64
 9   Measure Name          64764 non-null  object
 10  Measure ID            64764 non-null  object
 11  Compared to National  64764 non-null  object
 12  Denominator           64764 non-null  object
 13  Score                 64764 non-null  object
 14  Lower Estimate        64764 non-null  object
 15  Higher Estimate       64764 non-null  object
 16  Footnote              22979 non-null  object
 17  Measure Start Date    64764 non-null  object
 18  Measure End Date      64764 non-null  object
 19  Location              64764 non-null  object
dtypes: int64(4), object(16)
memory usage: 9.9+ MB

In [13]:
#Data Cleaning: removing null values, ensuring all data is in proper type, all numeric values are integers or floats
#Exploratory Data Analysis: determining what we can glean from this data
#Preprocessing and Modeling: build predictive model
#Data Visualization
#Data Storytelling

In [16]:
# dropping rows with missing numeric data

hospital_data = hospital_data[hospital_data['Denominator'] != 'Not Available']

In [19]:
hospital_data.dtypes

index                    int64
Provider ID              int64
Hospital Name           object
Address                 object
City                    object
State                   object
ZIP Code                 int64
County Name             object
Phone Number             int64
Measure Name            object
Measure ID              object
Compared to National    object
Denominator             object
Score                   object
Lower Estimate          object
Higher Estimate         object
Footnote                object
Measure Start Date      object
Measure End Date        object
Location                object
dtype: object

In [22]:
# converting numeric data to float64 dtype 

hospital_data['Denominator'] = pd.to_numeric(hospital_data['Score'])
hospital_data['Score'] = pd.to_numeric(hospital_data['Score'])
hospital_data['Lower Estimate'] = pd.to_numeric(hospital_data['Lower Estimate'])
hospital_data['Higher Estimate'] = pd.to_numeric(hospital_data['Higher Estimate'])

In [25]:
# changing data type of start data and end date to datetime dtype

hospital_data['Measure Start Date'] = pd.to_datetime(hospital_data['Measure Start Date'])
hospital_data['Measure End Date'] = pd.to_datetime(hospital_data['Measure End Date'])

In [28]:
hospital_data.dtypes

index                            int64
Provider ID                      int64
Hospital Name                   object
Address                         object
City                            object
State                           object
ZIP Code                         int64
County Name                     object
Phone Number                     int64
Measure Name                    object
Measure ID                      object
Compared to National            object
Denominator                    float64
Score                          float64
Lower Estimate                 float64
Higher Estimate                float64
Footnote                        object
Measure Start Date      datetime64[ns]
Measure End Date        datetime64[ns]
Location                        object
dtype: object

In [31]:
# removing columns irrelevant to data analysis

hospital_data = hospital_data.drop(columns=['Phone Number','Footnote', 'Provider ID', 'Address', 'ZIP Code', 'Phone Number', 'Location' ], axis=1)

In [33]:
hospital_data.head()

,index,Hospital Name,City,State,County Name,Measure Name,Measure ID,Compared to National,Denominator,Score,Lower Estimate,Higher Estimate,Measure Start Date,Measure End Date
0,0,TAWAS ST JOSEPH HOSPITAL,TAWAS CITY,MI,IOSCO,Rate of readmission after discharge from hospi...,READM_30_HOSP_WIDE,No Different than the National Rate,13.9,13.9,12.6,15.6,2014-07-01,2015-06-30
1,1,MEMORIAL HEALTHCARE,OWOSSO,MI,SHIAWASSEE,Rate of readmission after hip/knee replacement,READM_30_HIP_KNEE,No Different than the National Rate,4.0,4.0,2.8,5.7,2012-07-01,2015-06-30
2,2,HURON MEDICAL CENTER,BAD AXE,MI,HURON,Pneumonia (PN) 30-Day Readmission Rate,READM_30_PN,No Different than the National Rate,16.7,16.7,13.8,19.9,2012-07-01,2015-06-30
3,3,MEMORIAL HEALTHCARE,OWOSSO,MI,SHIAWASSEE,Rate of readmission for stroke patients,READM_30_STK,No Different than the National Rate,11.5,11.5,8.7,14.9,2012-07-01,2015-06-30
4,4,OTSEGO MEMORIAL HOSPITAL,GAYLORD,MI,OTSEGO,Heart failure (HF) 30-Day Mortality Rate,MORT_30_HF,No Different than the National Rate,13.4,13.4,9.9,17.7,2012-07-01,2015-06-30

In [70]:
#Format Data so only state, measure, and score are present
HD = hospital_data[["Measure Name", "Measure ID", "State", "Score"]]

In [87]:
#Reformat HD so that we can view the MEAN Score data for each Measure Name by State
# Convert 'Score' column to numeric, forcing errors to NaN
HD['Score'] = pd.to_numeric(HD['Score'], errors='coerce')

# Check for non-numeric values that were converted to NaN
print(HD[HD['Score'].isna()])

# Drop rows where 'Score' is NaN (if any)
HD = HD.dropna(subset=['Score'])

# Aggregate the data to handle duplicates, here we take the mean of scores
# Make sure to exclude non-numeric columns from the aggregation
numeric_cols = HD.select_dtypes(include='number').columns
aggregated_HD = HD.groupby(['State', 'Measure Name'])[numeric_cols].mean().reset_index()

# Pivot the DataFrame
pivoted_HD = aggregated_HD.pivot(index='State', columns='Measure Name', values='Score')

# Reset the index to turn 'State' back into a column
pivoted_HD.reset_index(inplace=True)

# Sort the DataFrame by 'State'
pivoted_HD.sort_values(by='State', inplace=True)

# Display the reshaped DataFrame
pivoted_HD.head()

Empty DataFrame
Columns: [Measure Name, Measure ID, State, Score]
Index: []

Measure Name,State,Acute Myocardial Infarction (AMI) 30-Day Mortality Rate,Acute Myocardial Infarction (AMI) 30-Day Readmission Rate,Death rate for CABG,Death rate for chronic obstructive pulmonary disease (COPD) patients,Death rate for stroke patients,Heart failure (HF) 30-Day Mortality Rate,Heart failure (HF) 30-Day Readmission Rate,Pneumonia (PN) 30-Day Mortality Rate,Pneumonia (PN) 30-Day Readmission Rate,Rate of readmission after discharge from hospital (hospital-wide),Rate of readmission after hip/knee replacement,Rate of readmission for CABG,Rate of readmission for chronic obstructive pulmonary disease (COPD) patients,Rate of readmission for stroke patients
0,AK,13.260000,16.360000,2.950000,8.316667,15.871429,13.137500,21.588889,17.238462,16.369231,15.129412,4.762500,13.700000,19.791667,12.214286
1,AL,14.766667,17.128571,4.000000,8.086076,15.338333,12.338158,21.900000,17.319277,17.234940,15.450000,4.951163,14.700000,19.727500,12.949153
2,AR,14.643333,17.312500,4.247059,8.516129,15.654348,13.312500,22.744615,17.594286,17.395652,15.844444,4.700000,14.776471,20.492063,12.777273
3,AZ,13.988889,16.631818,3.277778,8.274074,15.064286,11.613725,21.466667,15.528788,16.849254,15.322222,4.625000,14.407407,19.690909,12.202381
4,CA,13.700483,16.908901,3.033333,8.052964,14.522078,11.607547,22.001504,15.978014,17.222887,15.539937,4.479126,14.278723,19.923346,12.560352

In [ ]:
#create barplot
HD_MI = plt.bar(x="State", 
                
                ##Question: Are readmission and mortality rates associated with income? incorporate data frame of zipcodes with median income and compare readmission/death rates for each disease to see if there is a relationship between the socioeconomic status of the area that the hospital is in with patient outcomes